# WARNING: Make sure the project-folder-name is unique on your server!
# You should disable port-exposure in production!

networks:
    main-proxy:
        external: true

volumes:
    db_volume:
    redis_volume:
    meili_volume:
    claude_home:

services:
    # docker compose exec -it php_ai claude
    # docker compose exec -it php_ai bash
    php:
        image: ghcr.io/jonaaix/laravel-aio:1.3-php8.5-fpm-claude
        stop_grace_period: 60s
        volumes:
            - ./:/app
            - claude_home:/home/laravel
        environment:
            ENV_DEV: true
            DEV_NPM_RUN_DEV: true
            ENABLE_HORIZON_WORKER: true
            ENABLE_REVERB_SERVER: true
            ENABLE_CLAUDE_THREADS: true
            ENABLE_AI_NONTECH_MODE: true
        labels:
            caddy_0: ${LARAVEL_DOMAIN}
            caddy_0.reverse_proxy: "{{upstreams 8000}}"
            caddy_0.encode: zstd gzip

            caddy_1: ws.${LARAVEL_DOMAIN}
            caddy_1.reverse_proxy: "{{upstreams 8080}}"

            caddy_2: vite.${LARAVEL_DOMAIN}
            caddy_2.reverse_proxy: "{{upstreams 5178}}"
        restart: unless-stopped
        networks:
            - main-proxy
            - default
        depends_on:
            - mariadb
            - redis

    mariadb:
        image: mariadb:lts
        command:
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
            - '--skip-name-resolve' # Disable DNS lookups (not needed in Docker, improves performance)
        volumes:
            - db_volume:/var/lib/mysql/:delegated
        cap_add:
            - SYS_NICE # Allow the container to adjust process priority (optional for performance tuning)
        environment:
            MARIADB_INITDB_SKIP_TZINFO: '1' # Skip loading DB time zone tables (improves performance)
            ### Database initialization ###
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
        restart: unless-stopped

    redis:
        image: redis:7-alpine
        volumes:
            - redis_volume:/data
        command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
        restart: unless-stopped

    meilisearch:
        image: getmeili/meilisearch:latest
        environment:
            MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
            MEILI_NO_ANALYTICS: "true"
            MEILI_ENV: "development"
        volumes:
            - meili_volume:/meili_data
        restart: unless-stopped

    pma:
        image: phpmyadmin:latest
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            APACHE_PORT: 8080
            UPLOAD_LIMIT: 1G
        restart: unless-stopped
        labels:
            caddy: ${PMA_DOMAIN}
            caddy.reverse_proxy: "{{upstreams 8080}}"
        networks:
            - main-proxy
            - default
        depends_on:
            - mariadb
